import React from 'react';
import {Accordion,Card,Button }from 'react-bootstrap';
// import Sidebar from 
const  item  = ({Name,Qty,Nos,img,
     Design,   HSN,  Fabric,  Print,  Color  ,QTYinStock, Make,  Remark , 
     BillNo ,  BillDate,  OrderDate,BiltyNo, Rate, 
     InChlaanNo , ChallanDate , Transporter  ,VcNo, GenratedBy }) =>{
    
    return(
        <div className="inventoryItem">
            <Accordion>
                <Card>
                    <Card.Header>
                    <Accordion.Toggle  as={Card.Header}    variant="link" eventKey="0">

                        <div className='inventory-item-list'>
                            <div className="inventory-item-img">
                                <img src={img} alt="" srcset=""/>
                            </div>
                            
                        <div className="inventory-item-list-info">
                                <div className="inventory-item-Name">
                                Name:  {Name}
                                </div>
                                <div className="challan-item-qty">
                                Qty:  {Qty}
                                </div>
                                <div className="inventory-item-Nos">
                                Nos:  {Nos}
                                </div>
                        </div>
                           
                    
                        </div>
                        
                        

                    </Accordion.Toggle>
                    </Card.Header>
                    <Accordion.Collapse eventKey="0">
                    <Card.Body>
                        <div className="inventory_item_details">
                            <div className="inventory_item_details_1 inventory_item_details_info ">
                                <ul>
                                    <li>Name: {Name}</li>
                                    <li>Design: {Design}</li>
                                    <li>HSN: {HSN}</li>
                                    <li>Fabric: {Fabric}</li>
                                    <li>Print: {Print}</li>
                                    <li>Color: {Color}</li>
                                    <li>QTY in Stock: {QTYinStock}</li>
                                    <li>Make: {Make}</li>
                                    <li>NOS: {Nos}</li>
                                    <li>Remarks: {Remark}</li>
                                
                                </ul>

                            </div>
                            <div className="inventory_item_details_2 inventory_item_details_bill">
                                <ul>
                                    <li>BillNo: {BillNo}</li>
                                    <li>Bill Date: {BillDate}</li>
                                    <li>OrderDate: {OrderDate}</li>
                                    <li>BiltyNo: {BiltyNo}</li>
                                    <li>Rate: Rs.{Rate}</li>
                                
                                </ul>


                            </div>
                            <div className="inventory_item_details_3 inventory_item_details_inChllan">
                                <ul>
                                    <li>In Challan No: {InChlaanNo}</li>
                                    <li>ChallanDate: {ChallanDate}</li>
                                    <li>Transporter: {Transporter}</li>
                                    <li>Vechicle Number: {VcNo}</li>
                                    <li>Generated By: {GenratedBy}</li>
                                
                                </ul>
                            
                            </div>  


                        </div>


                    </Card.Body>
                    </Accordion.Collapse>
                </Card>
              
            </Accordion>

       
        </div>
    )
}

export default item